[mgr]
show_hidden = true  # show hidden files by default
show_symlink = true # umm also... something to do with .gitignore

# D removes files permanently
# d trashes (trash is to be found in ~/.local/share/Trash)
[[manager.prepend_keymap]]
on = ['D']
run = 'remove --permanently'
